### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by mikrobi** [wollerr/freejodel#1]

**Comment by Powersource** [comment]
Since this was the first result on google and still has no code I'll take the freedom to link to these other projects:  
- A desktop client that seems feature rich https://bitbucket.org/cfib90/ojoc/overview
- A node package for accessing the api https://github.com/Hanse/node-jodel (there's also a fork that's more recently active)
- Someone's made a small wiki with api information and more http://jodel-app.wikia.com/wiki/Jodel_App_Wikia
- Statistics https://github.com/ppati000/jodelstats
- Another less active desktop client https://github.com/flopp/DesktopJodel
